Fix/backend bugs
EnergyTea/Web-Sql-Git pull request #19
Opened 2020-10-26 23:55 UTC by EnergyTea

2020-10-26 23:57 UTC, EnergyTea commented
Нужно добавить стиль Отображение Категории и Тегов. Не совсем понял как и куда их поставить по этому просто получил вывел.

2020-10-27 07:42 UTC, igor-dev13 requested changes
> Нужно добавить стиль Отображение Категории и Тегов. Не совсем понял как и куда их поставить по этому просто получил вывел.
- Нужно подумать, как это сделать лучше, чтобы текст не сливался. Например названия категорий вывести сверху от текста скрипта, теги под тестом скрипта и шрифт для них сделать меньше и жирный.

---
2. В модели Category.cs есть свойство isAutorize, которое не используется, но нет Deleted, которое используем. (Бекенд, фронтенд)
Не поправлено. http://prntscr.com/v7mgmy

4. Нет возможности поиска по тегам.
Вижу что возможность появилась, классно. http://prntscr.com/v7mi2t
Давай подправим, будем выводить не полное описание, а допустим первые 6 слов, чтобы результатов помещалось больше, если скриптов будет больше они не влезут. Нужно будет проверить, чтобы влазило 10 - 12 скриптов.

7. При переходе в редактирование, уехала кнопка сохранить 
Кнопка там же. Возможно у тебя разрешение на мониторе меньше. Покрути колесико мыши, кнопка должна уехать.  http://prntscr.com/v7mned

8. Сделать стили кнопки сохранить одинаковыми. Хорошо смотрятся кнопки на странице просмотра скрипта.
Мне кажется, стили отличаются. http://prntscr.com/v7mned http://prntscr.com/v7mody

10. Ширина заголовка при просмотре скрипта маленькая http://prntscr.com/v3m6ow
Предлагаю заголовок сделать по всей ширине, а теги сместить на следующую строку. http://prntscr.com/v7mpsh

11. Давай выведем название категории у списка скриптов, для наглядности, примерно вот так (сделать не красным конечно) http://prntscr.com/v3m8e7
Категорию нужно как-то отделить от описания. Все сливается http://prntscr.com/v7mque
Предлагаю категорию вывести сверху описания с небольшим отступом от него и сделать их шрифтом поменьше.

12. Давай и теги так же выведем, мелким тестом, примерно так же.
Тоже самое, что и в 11.
Предлагаю теги вывести снизу описания с небольшим отступом от него и сделать их шрифтом поменьше.

13. Отличается стили главной страницы и страницы отдельной категории. http://prntscr.com/v3mhz1
http://prntscr.com/v7npbu

14. Если название скрипта большое, налазит название на строку следующего скрипта. http://prntscr.com/v3mz5s 
Поправить, чтобы выглядело хорошо http://prntscr.com/v7nr3a

----------------------------

1. При добавлении тега падает ошибка в консоле http://prntscr.com/v7nvha
2. Какая то тут беда с тегами похоже http://prntscr.com/v7nxpe 
 
После внесения правок, желательно еше раз пройтись, перепроверить, что все сделано и работает, перед пушем.
Если правишь ui часть, стили, отступы, шрифты. Смотри, чтобы после правок тебе самому нравилось.

2020-10-27 07:42 UTC, igor-dev13 commented on WebSqlGit/ClientApp/src/app/scripts/script-create/script-create.component.ts
> +    if (tagNew !== "" && this.tags.length < 5) {
думаешь больше 4 тегов не будет?

2020-11-01 10:14 UTC, EnergyTea commented on WebSqlGit/ClientApp/src/app/scripts/script-create/script-create.component.ts
> +    if (tagNew !== "" && this.tags.length < 5) {
Мне кажется, большее количество нагромождает. Их 5шт ведь) 
Если нужно можно увеличить. Увеличу до 8

2020-11-02 08:51 UTC, igor-dev13 commented
> Нужно добавить стиль Отображение Категории и Тегов. Не совсем понял как и куда их поставить по этому просто получил вывел.
Тут сейчас все ок

2020-11-02 08:54 UTC, igor-dev13 commented
При переходе в редактирование, уехала кнопка сохранить
Кнопка там же. Возможно у тебя разрешение на мониторе меньше. Покрути колесико мыши, кнопка должна уехать. http://prntscr.com/v7mned
Этот пункт сделать обязательно.

На странице скриптов для конкретного скрипта выводятся теги от другого скрипта. 
Видимо, нужно создать несколько скриптов, чтобы повторить баг.
http://prntscr.com/vbo1jb перехожу а реальные теги у него http://prntscr.com/vbo26i
Этот пункт сделать обязательно.

Отличается стили страницы скриптов пользователя и страницы категории. + на странице скриптов пользователя вывести теги и категории.
http://prntscr.com/vbnzww
Этот пункт сделать желательно. Если времени уйдет много, можно пока оставить.

При добавлении тега падает ошибка в консоле http://prntscr.com/v7nvha
Этот пункт сделать желательно. Если времени уйдет много, можно пока оставить.

2020-11-03 06:23 UTC, igor-dev13 commented
1. Предлагаю эту колонку сделать пошире
http://prntscr.com/vcbsvy

2. Если кликать на отдельный скрипт на странице скриптов http://prntscr.com/vcbu2v
При переходе не отображается категория http://prntscr.com/vcbu7c (нет подсветки активной категории)

3. Поля для тегов ограничены по ширине http://prntscr.com/vcbwbe

4. Уехала кнопка создания скрипта http://prntscr.com/vcbxjw

5. Я создал категорию, создал для нее скрипт. Перешел в скрипт со страницы скриптов. Далеее перешел в редактирование скрипта.
http://prntscr.com/vcbygb

6. При наведении на элемент не отображается курсор лапка, не очень понятно, что элемент кликабелен http://prntscr.com/vcbzjx

7. Постараться хорошо протестировать приложение. Создать большие и маленькие скрипты с большими и маленькими тегами и категориями, все должно отображается на своих местах.

2020-11-03 07:37 UTC, EnergyTea commented
1 - исправил
2 - под вопросом реализации
3 - исправил
4 - исправил
5 - у меня нет такого бага. (буду ещё тестить)
6 - исправил

2020-11-04 07:30 UTC, igor-dev13 commented
пункты 2 и 5
Похоже проблема в том, что категории приходят позже чет сам скрипт, 
![image](https://user-images.githubusercontent.com/18236490/98081489-3f38ba80-1e88-11eb-8e70-cf62597e745c.png) попробуй посмотреть в эту сторону.

Пункт 4 у меня кнопка отображается так же http://prntscr.com/vcbxjw

2020-11-08 06:55 UTC, igor-dev13 commented
Предлагаю пока скрыть, раз там выводим те же скрипты, что и на основной странице.
http://prntscr.com/vfga66

Давай сделаем хотябы с новой строки и подпишем, что это категория,
а для строки тегов, подпишем, что это теги
http://prntscr.com/vfgb6f

Давай тут отступы добавим, чуть меньше чем у кнопок
http://prntscr.com/vfgdej

Вроде бы убирали возможность редактировать предыдущие скрипты?
http://prntscr.com/vfgdpt

Давай тут тоже лапку курсор добавим
http://prntscr.com/vfgebm

2020-11-09 09:57 UTC, EnergyTea commented
Предлагаю пока скрыть, раз там выводим те же скрипты, что и на основной странице.
(Скрыл ссылку)

Давай сделаем хотябы с новой строки и подпишем, что это категория,
а для строки тегов, подпишем, что это теги
(Добавил. Подписал)

Давай тут отступы добавим, чуть меньше чем у кнопок
(Добавил)

Вроде бы убирали возможность редактировать предыдущие скрипты?
(Поправил)

Давай тут тоже лапку курсор добавим
(Добавил)

2020-11-09 10:52 UTC, merged

2020-11-09 10:56 UTC, igor-dev13 commented
Accepted